version: '3.8'

services:
  backend:
    image: po-app-backend-image
    container_name: po_app_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://po_app_user:60MoG2$hKgvg&jsc@db/po_data_app
    depends_on:
      db: # <-- MODIFIED SECTION
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: po_app_db
    restart: always
    healthcheck: # <-- ADD THIS ENTIRE SECTION
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: 7rhctg2t9K9sB5a3
      MYSQL_DATABASE: po_data_app
      MYSQL_USER: po_app_user
      MYSQL_PASSWORD: 60MoG2$hKgvg&jsc
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: