version: '3.8'

services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: po_app_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://po_app_user:60MoG2$hKgvg&jsc@db/po_data_app
    depends_on:
      db: # <-- MODIFIED SECTION
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: po_app_db
    ports: # <-- ADD THIS SECTION
      - "3307:3306" # Maps container port 3306 to host port 3307
  
    restart: always
    healthcheck: # <-- ADD THIS ENTIRE SECTION
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: 7rhctg2t9K9sB5a3
      MYSQL_DATABASE: po_data_app
      MYSQL_USER: po_app_user
      MYSQL_PASSWORD: 60MoG2$hKgvg&jsc
    volumes:
      - mysql_data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: po_app_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1  # <-- ADD THIS LINE
volumes:
  mysql_data:
